### PR TITLE
add a wait output

### PR DESCRIPTION
**Pull request by milesmatthias**
This PR also fixes lint exclude dirs option.

### CODE REVIEW

**Comment by taylorludwig** [comment]
Do we need to add the `run_command` to the wait variable? https://github.com/terraform-google-modules/terraform-google-gcloud/blob/master/main.tf#L34

**Comment by milesmatthias** [comment]
> Do we need to add the `run_command` to the wait variable? https://github.com/terraform-google-modules/terraform-google-gcloud/blob/master/main.tf#L34

It wasn't necessary for what I was doing because waiting for those steps gave it enough time to complete the run command, but you're right, we should add that to ensure that we've waited for the command to finish.

**Comment by milesmatthias** [comment]
@taylorludwig @morgante this should be ready to merge.

**Comment by taylorludwig** [comment]
Actually @milesmatthias looks like the lint command fails after your last commit. https://console.cloud.google.com/cloud-build/builds/a786b6d8-3fb2-45d3-8b69-0440ca077699?project=cloud-foundation-cicd&angularJsUrl=%2Fcloud-build%2Fbuilds%2Fa786b6d8-3fb2-45d3-8b69-0440ca077699%3Fproject%3D2843445864&authuser=3

**Comment by milesmatthias** [comment]
@taylorludwig actually I think the lint for this PR was successful, but github's UI here is poor. I referenced this PR in comments for a commit that did not pass: https://github.com/terraform-google-modules/terraform-google-gcloud/commit/2bef4b26b5b9ad7a80e50bed5473610bb2b5918b

**Pull request merged**
