### PR TITLE
ship jq with this module and allow you to use it as a cmd entrypoint

### PR DESCRIPTION
**Pull request by milesmatthias**

### CODE REVIEW

**Comment by milesmatthias** [comment]
The linting error here is because the JQ binaries have a trailing whitespace. The best way to handle this is to add the `cache` directory to the ignored folders for the dev tools when checking whitespace & formatting, so see https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/471

**Comment by morgante** [comment]
@milesmatthias If you update to the latest dev tools image it should be fixed.

**Comment by milesmatthias** [comment]
Hmmm... maybe I didn't add that correctly?

```
Status: Downloaded newer image for gcr.io/cloud-foundation-cicd/cft/developer-tools:0.6.0
gcr.io/cloud-foundation-cicd/cft/developer-tools:0.6.0
Checking for documentation generation
Checking for trailing whitespace
Binary file ./cache/linux/jq matches
Binary file ./cache/darwin/jq matches
Error: Trailing whitespace found in the lines above.
```

**Comment by morgante** [comment]
I'm not sure if it's recursive?

You can try iterating locally (with `make build-image-developer-tools` on the cft repo + `make docker_test_lint` on this one) until it works, no need to wait for Cloud Build feedback.

**Comment by milesmatthias** [comment]
Waiting for https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/509 to be merged.

**Pull request merged**
